services:
- name: "OP001"
  service: "http://localhost:8081/client/"
- name: "OP002"
  service: "http://localhost:8081/client/"
- name: "OP003"
  service: "http://localhost:8081/client/"
- name: "OP004"
  service: "http://localhost:8081/client/"
- name: "OP005"
  service: "http://localhost:8081/client/"
- name: "OP006"
  service: "http://localhost:8081/client/"
- name: "OP007"
  service: "http://localhost:8081/client/"
- name: "OP008"
  service: "http://localhost:8081/client/"
- name: "OP009"
  service: "http://localhost:8081/client/"
- name: "OP010"
  service: "http://localhost:8081/client/"
- name: "OP011"
  service: "http://localhost:8081/client/"
- name: "OP012"
  service: "http://localhost:8081/client/"
- name: "OP013"
  service: "http://localhost:8081/client/"
- name: "OP014"
  service: "http://localhost:8081/client/"
- name: "OP015"
  service: "http://localhost:8081/client/"
- name: "OP016"
  service: "http://localhost:8081/client/"
- name: "OP017"
  service: "http://localhost:8081/client/"
- name: "OP018"
  service: "http://localhost:8081/client/"
- name: "OP019"
  service: "http://localhost:8081/client/"
- name: "OP020"
  service: "http://localhost:8081/client/"
- name: "OP021"
  service: "http://localhost:8081/client/"
- name: "OP022"
  service: "http://localhost:8081/client/"
- name: "OP023"
  service: "http://localhost:8081/client/"
- name: "OP024"
  service: "http://localhost:8081/client/"
- name: "OP025"
  service: "http://localhost:8081/client/"